### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by claustromaniac** [maxine-red/alex#4]
It's an interesting concept but I wish I could know a bit more about it without having to delve into the source code. At the very least enough to decide if I can trust this extension to be secure and private.

I also want to point out that the link to [reinforcejs](https://github.com/karpathy/reinforcejs) in the description [here](https://addons.mozilla.org/en-US/firefox/addon/alex_ai/?src=cb-dl-created) is broken.

**Comment by maxine-red** [comment]
Thank you for letting me know! I address both in the next code update.

**Comment by maxine-red** [comment]
Added documentation in the README.md. It is currently only available in the development tree, but will be merged into master next time.
